### ISSUE TITLE
Maplist in practicemode.cfg doesn't take effect in .map menu

### ISSUE THREAD

**Issue by cybersteel8** [splewis/csgo-practice-mode#60]
### Expected behavior
The menu that appears when you type .map ingame should display the list in practicemode.cfg

### Actual behavior
The default list appears:
de_cache
de_cbble
de_dust2
de_inferno
de_mirage
de_nuke
de_overpass
de_train

### Steps to reproduce
Stop server, comment out various lines in practicemode.cfg in the maps section, to only have 2 maps active (for example). Start server, join it, type .map in chat and view the list that appears.
- Plugin version: 1.2.1
- Sourcemod version: 1.8.0.6040

**Comment by splewis** [comment]
Thanks for the bug report -- this should be fixed now.

**Comment by cybersteel8** [comment]
Hi, thanks for the quick action. I grabbed that .sp file you changed and replaced the existing one on my server with your new one. The bug appears to remain. I tried commenting out various lines with `//` but they all seem to appear.
This is what my practicemode.cfg file looks like. It appears that de_dust isn't in the list, but the rest are still showing up (cs_italy is not).
`
"practice_settings"
{
        "maps"
        {
                "de_cache"              ""
                "de_cbble"              ""
//              "de_dust"               ""
                "de_dust2"              ""
//              "de_inferno"            ""
//              "de_mirage"             ""
//              "de_nuke"               ""
//              "de_overpass"           ""
//              "cs_italy"              ""
        }
[...]
`

**Comment by splewis** [comment]
That's because changing the source code without recompiling won't do anything. If you want the fix now you should download from https://ci.splewis.net/job/csgo-practice-mode/lastSuccessfulBuild/

**Comment by cybersteel8** [comment]
So I gave the new build a try, and it seems that only the first map (in my case, de_cache) is appearing on the list. I have the same config as I provided earlier - there should be three maps in the list.

And while I do not know if this is a symptom of this issue, there is a problem in the Practice Settings panel, as you can see in my ![provided screenshot.](https://user-images.githubusercontent.com/17291212/35204140-51265628-ff80-11e7-8e7c-d05071960b37.png)

**Comment by splewis** [comment]
Ugh, I probably messed up. I'll check again.

**Comment by cybersteel8** [comment]
It appears you fixed it in commit [3c2784f](https://github.com/splewis/csgo-practice-mode/commit/3c2784f8bb4a9fb7cd9e64c63294c4533b354d31). I am able to both comment out lines, and add new entries to different maps and change to them using the menu. Thank you very much for addressing this issue.

However, the other issue with option 2 being empty (as per previous screenshot) in the menu persists. I can make a new issue for it if you like. I don't know if it is related to this issue or not.

**Comment by cybersteel8** [comment]
I found out how that option became visible. There's a "changeable" flag right under the maps are that I set to 1 when it should remain at zero. Setting it back to zero removed that option in the in-game menu.

**Comment by cybersteel8** [comment]
@splewis Quick question on this topic - what do the second pair of quotations mean in the maps section of practisemode.cfg ? I was hoping it would be a display name/alias of the map name that shows up in the menu, but that isn't it... what're they for? If nothing, I might have a feature request for ya :)

**Comment by splewis** [comment]
They don't do anything. The file format is just in [keyvalues](https://developer.valvesoftware.com/wiki/KeyValues) so it needs a value to parse. I'm fine if someone wants to submit a pull request to add a display name there, but I'm not planning to add that myself.
